### ISSUE TITLE
depracated code & routes failing to be generated

### ISSUE THREAD

**Issue by doughnet** [tanc/gridsome-cockpit-source#2]
I know that my API permissions are correct.  I have a fresh Gridsome installation so nothing else should be effecting the plugin.  Below are my files & details.

I'm expecting to have the items in collection "example" to have a page generated for each.  Also, documentation lacks information about templates ... do I need a file in templates/Example.vue for example?  

// my file gridsome.conf.js
`
module.exports = {
  siteName: 'Cockpit API Testing',
  templates: {
    },
  plugins: [
      {
        use: '@tanc00/gridsome-source-cockpit',
        options: {
          accessToken: process.env.ACCESSTOKEN,
          host: process.env.APIHOST,
          routes: {
            example: '/example/:firstName',
          }
        }
      }
    ]
}
`

**Output when running yarn develop** 
Initializing plugins...
CockpitExample > Failed to add node: Duplicate key for property path: /example/first-name/
CockpitExample > Failed to add node: Duplicate key for property path: /example/first-name/
CockpitExample > Failed to add node: Duplicate key for property path: /example/first-name/

**Cockpit API Output From /api/collections/get/example** 
`
{"fields":{"firstName":{"name":"firstName","type":"text","localize":false,"options":[]},"lastName":{"name":"lastName","type":"text","localize":false,"options":[]}},"entries":[{"firstName":"Bris","lastName":"Gard","_mby":"5f2aec6ab26a702cec121801","_by":"5f2aec6ab26a702cec121801","_modified":1596649014,"_created":1596649014,"_id":"5f2aee36acab7b677e6f28e1"},{"firstName":"Robert","lastName":"Vag","_mby":"5f2aec6ab26a702cec121801","_by":"5f2aec6ab26a702cec121801","_modified":1596649039,"_created":1596649033,"_id":"5f2aee490df6ec4c8262b021"},{"firstName":"Marty","lastName":"McFly","_mby":"5f2aec6ab26a702cec121801","_by":"5f2aec6ab26a702cec121801","_modified":1596649049,"_created":1596649049,"_id":"5f2aee59e9d29d3429164b71"},{"firstName":"Skye","lastName":"Varner","_mby":"5f2aec6ab26a702cec121801","_by":"5f2aec6ab26a702cec121801","_modified":1596649055,"_created":1596649055,"_id":"5f2aee5f18d089534b1ce9a1"}],"total":4}
`

**Comment by tanc** [comment]
> Output when running yarn develop

Have you tried `gridsome develop`? Do you get the same errors?

**Comment by tanc** [comment]
No response so closing.
